<a href="https://colab.research.google.com/github/2303A51125/B3_PFDS_1125/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
b = np.array([[1,2],[3,4]])
print(b)
c = np.zeros((2,2))
print(c)
d = np.ones((2,3))
print(d)

[1 2 3 4]
[[1 2]
 [3 4]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#RANGE OF NUMBERS
range_arr = np.arange(0,10,2)
print("RangeArray:",range_arr)

RangeArray: [0 2 4 6 8]


In [7]:
#RANDOM ARRAY
rand_arr = np.random.rand(2,3)
print("RandomArray:\n",rand_arr)

RandomArray:
 [[0.2256691  0.41586953 0.6624834 ]
 [0.8146635  0.53706363 0.78963036]]


In [9]:
#ATTRIBUTES OF ARRAY
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

(2, 3)
2
int64
6
8


In [11]:
#ARRAY INDEXING AND SLICING
a = np.array([10,20,30,40,50])
print(a[2])
print(a[3])
print(a[-1])
print(a[1:3])
print(a[::2])
print(a[1::])

30
40
50
[20 30]
[10 30 50]
[20 30 40 50]


In [14]:
#2D ARRAY
a = np.array([[10,20,30],[40,50,60]])
print(a[1][1])
print(a[0:1])
print(a[1::])
print(a[::1])

50
[[10 20 30]]
[[40 50 60]]
[[10 20 30]
 [40 50 60]]


In [15]:
#ARITHEMATIC OPERATIONS
a = np.array([1,2,3])
b= np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a**b)
print(a/b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]


In [17]:
#AGGREGATE FUNCTIONS
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.mean(a))
print(np.std(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

21
6
1
3.5
1.707825127659933
[5 7 9]
[ 6 15]


In [19]:
#BROADCASTING
a = np.array([1,2,3])
b = 5
print(a+b)
c = np.array([[1],[2],[3]])
d = np.array([4,5,6])
print(c+d)

[6 7 8]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
